/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics.tables;


import com.oleg.fund.customer.costs.analytics.Public;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerCostsCategory extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.customer_costs_category</code>
     */
    public static final CustomerCostsCategory CUSTOMER_COSTS_CATEGORY = new CustomerCostsCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.customer_costs_category.id</code>.
     */
    public final TableField<Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.customer_costs_category.description</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR.nullable(false), this, "");

    private CustomerCostsCategory(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerCostsCategory(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.customer_costs_category</code> table
     * reference
     */
    public CustomerCostsCategory(String alias) {
        this(DSL.name(alias), CUSTOMER_COSTS_CATEGORY);
    }

    /**
     * Create an aliased <code>public.customer_costs_category</code> table
     * reference
     */
    public CustomerCostsCategory(Name alias) {
        this(alias, CUSTOMER_COSTS_CATEGORY);
    }

    /**
     * Create a <code>public.customer_costs_category</code> table reference
     */
    public CustomerCostsCategory() {
        this(DSL.name("customer_costs_category"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return (Identity<Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(CustomerCostsCategory.CUSTOMER_COSTS_CATEGORY, DSL.name("customer_costs_category_pkey"), new TableField[] { CustomerCostsCategory.CUSTOMER_COSTS_CATEGORY.ID }, true);
    }

    @Override
    public CustomerCostsCategory as(String alias) {
        return new CustomerCostsCategory(DSL.name(alias), this);
    }

    @Override
    public CustomerCostsCategory as(Name alias) {
        return new CustomerCostsCategory(alias, this);
    }

    @Override
    public CustomerCostsCategory as(Table<?> alias) {
        return new CustomerCostsCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsCategory rename(String name) {
        return new CustomerCostsCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsCategory rename(Name name) {
        return new CustomerCostsCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCostsCategory rename(Table<?> name) {
        return new CustomerCostsCategory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsCategory where(Condition condition) {
        return new CustomerCostsCategory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsCategory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsCategory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsCategory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsCategory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsCategory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsCategory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCostsCategory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsCategory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCostsCategory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
