openapi: 3.0.0

info:
    version: 1.0.0
    title: Customer Costs Analytics Open API
paths:
    /analytics/periods:
        $ref: 'paths/period/analytics_periods.yaml'
    /period/{id}/costs/analytics/:
        $ref: 'paths/period/period_analytics.yaml'
    /categorized/{id}/costs/analytics/:
        $ref: 'paths/category/categorized_analytics.yaml'