version: '3.8'

services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
            - '2181:2181'
        volumes:
            - zookeeper_data:/bitnami

    customer-costs-kafka:
        image: 'bitnami/kafka:latest'
        container_name: customer-costs-kafka
        depends_on:
            - zookeeper
        environment:
            - KAFKA_CFG_NODE_ID=0
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_PROCESS_ROLES=controller,broker
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@customer-costs-kafka:9093
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,CONTROLLER://customer-costs-kafka:9093
        ports:
            - '9092:9092'
            - '9093:9093'
        volumes:
            - kafka_data:/bitnami

    kafka-init:
        image: bitnami/kafka:latest
        init: true
        depends_on:
            customer-costs-kafka:
                condition: service_started
        volumes:
            - ./create_topic.sh:/create_topic.sh
        command:
            - /bin/bash
            - -c
            - |
                chmod +x /create_topic.sh && \
                /create_topic.sh
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

    customer-costs-analytics-pg:
        image: 'postgres:15.0'
        container_name: customer-costs-analytics-pg
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=customer-costs-analytics
        ports:
            - '5432:5432'
        volumes:
            - analytics_postgres_data:/var/lib/postgresql/data

    customer-costs-pg:
        image: 'postgres:15.0'
        container_name: customer-costs-pg
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=customer-costs
        ports:
            - '5433:5432'
        volumes:
            - costs_postgres_data:/var/lib/postgresql/data

    customer-costs-generator:
        image: 'molodoyboy777/customer-costs-generator:304e92773dd2c0f85a7697a3b9fc22214e02e00e'
        container_name: customer-costs-generator
        depends_on:
            - customer-costs-kafka

    customer-costs-analytics-service:
        image: 'molodoyboy777/customer-costs-analytics-service:388b0ccb247ff23ead9f404a64626327952e350a'
        container_name: customer-costs-analytics-service
        depends_on:
            - customer-costs-kafka
            - customer-costs-analytics-pg
        environment:
            - OLEG_DATABASE_USERNAME=dev
            - OLEG_DATABASE_PASSWORD=dev
            - OLEG_KAFKA_HOST=customer-costs-kafka
            - OLEG_DATABASE_HOST=customer-costs-analytics-pg
        ports:
            - '8080:8080'
    customer-costs-analytics-redis:
        image: redis
        ports:
            - "6379:6379"
volumes:
    kafka_data:
    zookeeper_data:
    costs_postgres_data:
    analytics_postgres_data: