server:
    port: 8080
    shutdown: graceful
    max-http-request-header-size: 2MB

spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    application:
        name: 'customer-costs-analytic-service'
    datasource:
        name: customer-costs-analytics
        username: ${DB_USER}
        password: ${DB_USER}
        url: 'jdbc:postgresql://customer-costs-analytics-pg:5432/customer-costs-analytics'
        hikari:
            maximum-pool-size: 40
            connection-timeout: 2000
    kafka:
        consumer:
            auto-offset-reset: earliest
            max-poll-records: 100

        bootstrap-servers: customer-costs-kafka:9092
    flyway:
        out-of-order: true
        clean-disabled: true
        ignore-migration-patterns:
            - '*:missing'
            - '*:future'
springdoc:
    swagger-ui:
        path: /swagger-ui.html
oleg:
    kafka:
        customer-costs:
            id: customer-costs
            topic: public.customer-costs.v1
            consumer:
                group:
                    id: analytics.customer-costs.v1