/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics;


import com.oleg.fund.customer.costs.analytics.tables.CategorizedCostsAnalytics;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCosts;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCostsByCategory;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCostsByPeriod;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCostsCategory;
import com.oleg.fund.customer.costs.analytics.tables.PeriodCostsAnalytics;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.categorized_costs_analytics</code>.
     */
    public final CategorizedCostsAnalytics CATEGORIZED_COSTS_ANALYTICS = CategorizedCostsAnalytics.CATEGORIZED_COSTS_ANALYTICS;

    /**
     * The table <code>public.customer_costs</code>.
     */
    public final CustomerCosts CUSTOMER_COSTS = CustomerCosts.CUSTOMER_COSTS;

    /**
     * The table <code>public.customer_costs_by_category</code>.
     */
    public final CustomerCostsByCategory CUSTOMER_COSTS_BY_CATEGORY = CustomerCostsByCategory.CUSTOMER_COSTS_BY_CATEGORY;

    /**
     * The table <code>public.customer_costs_by_period</code>.
     */
    public final CustomerCostsByPeriod CUSTOMER_COSTS_BY_PERIOD = CustomerCostsByPeriod.CUSTOMER_COSTS_BY_PERIOD;

    /**
     * The table <code>public.customer_costs_category</code>.
     */
    public final CustomerCostsCategory CUSTOMER_COSTS_CATEGORY = CustomerCostsCategory.CUSTOMER_COSTS_CATEGORY;

    /**
     * The table <code>public.period_costs_analytics</code>.
     */
    public final PeriodCostsAnalytics PERIOD_COSTS_ANALYTICS = PeriodCostsAnalytics.PERIOD_COSTS_ANALYTICS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CategorizedCostsAnalytics.CATEGORIZED_COSTS_ANALYTICS,
            CustomerCosts.CUSTOMER_COSTS,
            CustomerCostsByCategory.CUSTOMER_COSTS_BY_CATEGORY,
            CustomerCostsByPeriod.CUSTOMER_COSTS_BY_PERIOD,
            CustomerCostsCategory.CUSTOMER_COSTS_CATEGORY,
            PeriodCostsAnalytics.PERIOD_COSTS_ANALYTICS
        );
    }
}
