/*
 * This file is generated by jOOQ.
 */
package com.oleg.fund.customer.costs.analytics;


import com.oleg.fund.customer.costs.analytics.tables.CategorizedCostsAnalytics;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCosts;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCostsByCategory;
import com.oleg.fund.customer.costs.analytics.tables.CustomerCostsCategory;
import com.oleg.fund.customer.costs.analytics.tables.PeriodCostsAnalytics;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.categorized_costs_analytics</code>.
     */
    public static final CategorizedCostsAnalytics CATEGORIZED_COSTS_ANALYTICS = CategorizedCostsAnalytics.CATEGORIZED_COSTS_ANALYTICS;

    /**
     * The table <code>public.customer_costs</code>.
     */
    public static final CustomerCosts CUSTOMER_COSTS = CustomerCosts.CUSTOMER_COSTS;

    /**
     * The table <code>public.customer_costs_by_category</code>.
     */
    public static final CustomerCostsByCategory CUSTOMER_COSTS_BY_CATEGORY = CustomerCostsByCategory.CUSTOMER_COSTS_BY_CATEGORY;

    /**
     * The table <code>public.customer_costs_category</code>.
     */
    public static final CustomerCostsCategory CUSTOMER_COSTS_CATEGORY = CustomerCostsCategory.CUSTOMER_COSTS_CATEGORY;

    /**
     * The table <code>public.period_costs_analytics</code>.
     */
    public static final PeriodCostsAnalytics PERIOD_COSTS_ANALYTICS = PeriodCostsAnalytics.PERIOD_COSTS_ANALYTICS;
}
