name: CI

on:
    pull_request:
        branches:
            - '*'
    push:
        branches:
            - 'master'
jobs:
    publish:
        name: Build and push docker image
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Set up JDK 21
                uses: actions/setup-java@v3
                with:
                    distribution: temurin
                    java-version: 21
            - name: Build & Push with Jib
              env:
                  IMAGE_VERSION: ${{ github.sha }}
              run: ./gradlew jib